# Generated by Django 4.2.6 on 2024-07-29 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_remove_jugador_fecha_nacimiento'),
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participacion',
            unique_together={('partido', 'jugador')},
        ),
    ]
