# Generated by Django 4.2.6 on 2024-07-28 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_inicializar_posiciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='fecha_nacimiento',
        ),
    ]
